from datetime import datetime
from typing import Any, Protocol

from app.schemas.providers import (
    CanonicalEntityMapping,
    DataQualityReport,
    OfficialResultEnvelope,
    ProviderCapability,
    ProviderCapabilityMatrix,
    ProviderIdentity,
    ProviderObservation,
    RawPayloadReference,
    TemporalAvailabilityMetadata,
)


class SportsDataProviderProtocol(Protocol):
    """Protocol-only contract for future provider adapters; no Phase 7 implementation."""

    def identity(self) -> ProviderIdentity: ...

    def health(self) -> dict[str, Any]: ...

    def capabilities(self) -> list[ProviderCapability]: ...

    def capability_matrix(self) -> ProviderCapabilityMatrix: ...

    def coverage(self) -> dict[str, Any]: ...

    def fetch_competitions(self) -> list[ProviderObservation]: ...

    def fetch_fixtures(self, window: dict[str, datetime]) -> list[ProviderObservation]: ...

    def fetch_fixture(self, fixture_id: str) -> ProviderObservation: ...

    def fetch_lineups(self, fixture_id: str) -> list[ProviderObservation]: ...

    def fetch_injuries(self, scope: dict[str, Any]) -> list[ProviderObservation]: ...

    def fetch_statistics(self, fixture_id: str) -> list[ProviderObservation]: ...

    def fetch_live_events(self, fixture_id: str, cursor: str | None = None) -> list[ProviderObservation]: ...

    def fetch_odds(self, event_id: str, market: str, as_of: datetime) -> list[ProviderObservation]: ...

    def normalize(self, raw_payload: RawPayloadReference) -> ProviderObservation: ...

    def map_entity(self, observation: ProviderObservation) -> CanonicalEntityMapping: ...

    def temporal_metadata(self, observation: ProviderObservation) -> TemporalAvailabilityMetadata: ...

    def quality_report(self, observation: ProviderObservation) -> DataQualityReport: ...


class OfficialResultVerifierProtocol(Protocol):
    """Protocol-only contract for future official result verification."""

    def verify_result(self, envelope: OfficialResultEnvelope) -> OfficialResultEnvelope: ...
