from typing import Final


OPPORTUNITY_PROBABILITY_THRESHOLD: Final = 0.70
OPPORTUNITY_DATA_QUALITY_THRESHOLD: Final = 65.0
OPPORTUNITY_TECHNICAL_CONFIDENCE_THRESHOLD: Final = 50.0
HALF_TIME_RECENT_WINDOW: Final = 5
HALF_TIME_MINIMUM_SAMPLE_PER_TEAM: Final = 3
HALF_TIME_H2H_LIMIT: Final = 5
HALF_TIME_H2H_MINIMUM_SAMPLE: Final = 3
HALF_TIME_H2H_MAX_WEIGHT: Final = 0.10
HALF_TIME_CONFIDENCE_CAP: Final = 65.0
HALF_TIME_QUALITY_CAP: Final = 85.0
MAX_DAILY_OPPORTUNITIES: Final = 12
MAX_ALTERNATIVES_PER_MATCH: Final = 2
OPPORTUNITY_MARKET_GROUPS: Final = {
    "FIRST_HALF_MORE_GOALS": "half_time",
    "SECOND_HALF_MORE_GOALS": "half_time",
    "EQUAL_HALF_GOALS": "half_time",
    "FIRST_HALF_OVER_0_5": "half_time",
    "SECOND_HALF_OVER_0_5": "half_time",
    "SECOND_HALF_OVER_1_5": "half_time",
    "HOME_OR_DRAW": "double_chance",
    "AWAY_OR_DRAW": "double_chance",
    "HOME_OR_AWAY": "double_chance",
}


__all__ = [
    "HALF_TIME_CONFIDENCE_CAP",
    "HALF_TIME_H2H_LIMIT",
    "HALF_TIME_H2H_MAX_WEIGHT",
    "HALF_TIME_H2H_MINIMUM_SAMPLE",
    "HALF_TIME_MINIMUM_SAMPLE_PER_TEAM",
    "HALF_TIME_QUALITY_CAP",
    "HALF_TIME_RECENT_WINDOW",
    "MAX_ALTERNATIVES_PER_MATCH",
    "MAX_DAILY_OPPORTUNITIES",
    "OPPORTUNITY_MARKET_GROUPS",
    "OPPORTUNITY_DATA_QUALITY_THRESHOLD",
    "OPPORTUNITY_PROBABILITY_THRESHOLD",
    "OPPORTUNITY_TECHNICAL_CONFIDENCE_THRESHOLD",
]
